version: '3.6'
services:
  web:
    image: nginx:latest
    ports:
        - "80:80"
    volumes:
        - /opt/docker/ohif-dcm4che-nginx/site.conf:/etc/nginx/nginx.conf
    links:
        - viewer
  mongo:
    image: "mongo:latest"
    ports:
      - "27017:27017"
  viewer:
    image: ohif/viewer:latest
    ports:
      - "3000:3000"
    links:
      - mongo
      - dcm4chee-arc
    environment:
      - MONGO_URL=mongodb://mongo:27017/ohif
    volumes:
      - /opt/docker/ohif-dcm4che-nginx/app.json:/app/app.json
  slapd:
    image: dcm4che/slapd-dcm4chee:5.5.2
    ports:
      - "389:389"
    env_file: docker-compose.env
    volumes:
      - /opt/docker/dcm4chee-arc/ldap:/var/lib/ldap
      - /opt/docker/dcm4chee-arc/slapd.d:/etc/ldap/slapd.d
  postgres:
    image: dcm4che/postgres-dcm4chee:5.5
    ports:
      - "5432:5432"
    env_file: docker-compose.env
    volumes:
      - /opt/docker/dcm4chee-arc/db:/var/lib/postgresql/data
  elasticsearch:
    image: elasticsearch:2.3
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - /opt/docker/dcm4chee-arc/elasticsearch:/usr/share/elasticsearch/data
  kibana:
    image: kibana:4.5
    ports:
      - "5601:5601"
    links:
      - elasticsearch:elasticsearch
  logstash:
    image: dcm4che/logstash-dcm4chee:5.5
    ports:
      - "12201:12201/udp"
      - "8514:8514"
    links:
      - elasticsearch:elasticsearch
  dcm4chee-arc:
    image: dcm4che/dcm4chee-arc-psql:5.5.2-logstash-secure-ui
    ports:
      - "8080:8080"
      - "9990:9990"
      - "11112:11112"
      - "2575:2575"
    env_file: docker-compose.env
    environment:
      JAVA_OPTS: "-Xms64m -Xmx512m -XX:MetaspaceSize=96M -XX:MaxMetaspaceSize=256m -Djava.net.preferIPv4Stack=true -Djboss.modules.system.pkgs=org.jboss.byteman -Djava.awt.headless=true"
      WILDFLY_CHOWN: /opt/wildfly/standalone /storage
      WILDFLY_WAIT_FOR: ldap:389 db:5432 logstash:8514
    links:
      - slapd:ldap
      - postgres:db
      - logstash:logstash
    volumes:
      - /opt/docker/dcm4chee-arc/storage:/storage
      - /opt/docker/dcm4chee-arc/wildfly:/opt/wildfly/standalone